services:
  app:
    build: .
    ports:
      - '8000:8000'
    networks:
      - esnet
    volumes:
      - .:/app
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      - INDEX_NAME=logs
      - ELASTICSEARCH_HOST=http://elastic:9200

  elastic:
    image: elasticsearch:8.11.1
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - esnet
    healthcheck:
      test: ['CMD-SHELL', 'curl -s http://localhost:9200 >/dev/null || exit 1']
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 40s

networks:
  esnet:
    driver: bridge # default docker network
